### ISSUE TITLE
Building failed in Xcode 6.0.1

### ISSUE THREAD

**Issue by boondiggle** [tracy454/ToDoLite-Swift#1]
I get 27 error's and 1 warning

**Comment by tracy454** [comment]
I'm not surprised. Apple keeps changing the definition of the language and return types for library calls. Just wait two more weeks and see what Xcode 6.1 breaks. I did this porting project (using Xcode 6 beta 4) as a learning exercise and to see if I liked this new language. Maybe when Apple stops the mutation of the month club, I might get serious about Swift and fix this demo code.
